version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE=laravel
      MYSQL_ROOT_PASSWORD=secret
    ports:
      - "3306:3306"
